server:
  port: 9000

spring:
  application:
    name: cloud-gateway
  config:
    import:
      - nacos:common-jwt.yaml
      - nacos:cloud-gateway.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true