server:
  port: 9006

spring:
  application:
    name: cloud-vform
  config:
    import:
      - nacos:common-db.yaml
#      - nacos:common-redis.yaml
#      - nacos:cloud-vform.yaml
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        namespace: public
#        group: DEFAULT_GROUP
#      config:
#        server-addr: localhost:8848
#        namespace: public
#        group: DEFAULT_GROUP
#        file-extension: yaml
#        refresh-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

knife4j:
  enable: true
  openapi:
    title: "VForm3 动态表单API"
    description: "VForm3 动态表单数据管理接口"
    version: 1.0.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.cloud.vform.controller