server:
  port: 9001

spring:
  application:
    name: cloud-system
  config:
    import: optional:nacos:cloud-system.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

knife4j:
  enable: true
  openapi:
    title: "系统管理API"
    description: "系统管理相关接口"
    version: 1.0.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.cloud.system.controller