server:
  port: 9003

spring:
  application:
    name: cloud-order
  config:
    import:
      - nacos:common-db.yaml
      - nacos:common-redis.yaml
      - nacos:cloud-order.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true