apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: cloud-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - name: nacos
        image: nacos/nacos-server:v2.2.0
        ports:
        - containerPort: 8848
        env:
        - name: MODE
          value: "standalone"
        - name: SPRING_DATASOURCE_PLATFORM
          value: "mysql"
        - name: MYSQL_SERVICE_HOST
          value: "mysql-service"
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        - name: MYSQL_SERVICE_DB_NAME
          value: "nacos_config"
        - name: MYSQL_SERVICE_USER
          value: "root"
        - name: MYSQL_SERVICE_PASSWORD
          value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-service
  namespace: cloud-model
spec:
  selector:
    app: nacos
  ports:
  - port: 8848
    targetPort: 8848
    nodePort: 30848
  type: NodePort