server:
  port: 9002

# JWT配置
jwt:
  secret: cloud-model-secret-key-2024
  expiration: 86400000 # 24小时
  header: Authorization
  prefix: Bearer

knife4j:
  enable: true
  openapi:
    title: "认证授权服务API"
    description: "认证授权相关接口"
    version: 1.0.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.cloud.auth.controller